insert into student (name, birth_date, address, gender) values ('Britney Lukehurst', '2000-11-01', '9827 Fordem Parkway', 'Female');
insert into student (name, birth_date, address, gender) values ('Vincents Hinchon', '1933-03-01', '3 Raven Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Bevvy Bowkett', '2006-08-15', '291 Buhler Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Leone Craster', '1951-02-13', '41 Farragut Circle', 'Female');
insert into student (name, birth_date, address, gender) values ('Jaye Govett', '1969-11-02', '61 Gale Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Yoko Pitford', '1963-10-30', '554 Green Ridge Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Alexandre Tingcomb', '1960-05-17', '2 Gerald Trail', 'Male');
insert into student (name, birth_date, address, gender) values ('Arvy Eckley', '2008-12-16', '9488 Oak Valley Street', 'Male');
insert into student (name, birth_date, address, gender) values ('Afton Turfus', '1976-09-30', '4844 Bowman Circle', 'Female');
insert into student (name, birth_date, address, gender) values ('Leighton Rigney', '1962-06-06', '9689 Utah Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Ardelle Fattori', '1907-12-09', '2455 La Follette Pass', 'Female');
insert into student (name, birth_date, address, gender) values ('Teresita Gurrado', '1950-10-15', '56610 Autumn Leaf Street', 'Female');
insert into student (name, birth_date, address, gender) values ('Domingo Browne', '2008-11-02', '968 Spenser Park', 'Male');
insert into student (name, birth_date, address, gender) values ('Seumas Howels', '1978-10-03', '769 Dexter Crossing', 'Male');
insert into student (name, birth_date, address, gender) values ('Coralie Allworthy', '2001-09-06', '67 Elgar Avenue', 'Female');
insert into student (name, birth_date, address, gender) values ('Tanney Siseland', '1962-02-10', '0 Surrey Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Kristoffer Woodberry', '1918-06-11', '480 Fuller Place', 'Non-binary');
insert into student (name, birth_date, address, gender) values ('Rebe Geary', '1919-08-01', '83570 Dapin Road', 'Female');
insert into student (name, birth_date, address, gender) values ('Constantina Bellini', '1932-05-02', '5903 Ronald Regan Alley', 'Female');
insert into student (name, birth_date, address, gender) values ('Jennine Nickels', '1912-04-15', '79595 Tomscot Lane', 'Female');
insert into student (name, birth_date, address, gender) values ('Tony Rizzello', '1903-11-05', '98 Beilfuss Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Annis Owbrick', '1978-08-04', '201 Schurz Hill', 'Female');
insert into student (name, birth_date, address, gender) values ('Nappy Patroni', '1959-01-20', '02725 Susan Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Saudra Sarney', '1998-06-11', '4 5th Parkway', 'Female');
insert into student (name, birth_date, address, gender) values ('Roddie Alldread', '1990-06-04', '041 Del Sol Park', 'Male');
insert into student (name, birth_date, address, gender) values ('Munroe Niblo', '1905-08-12', '85782 Lakewood Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Serge McLeary', '1928-10-27', '59 Florence Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Murdock Rafferty', '1921-01-10', '04 Sugar Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Rhoda Kock', '1992-12-19', '0 Schlimgen Circle', 'Female');
insert into student (name, birth_date, address, gender) values ('Gabriel Bissett', '1962-12-03', '790 Sunbrook Place', 'Male');
insert into student (name, birth_date, address, gender) values ('Nathanil Haston', '1928-07-10', '72106 Mockingbird Place', 'Male');
insert into student (name, birth_date, address, gender) values ('Niki Alennikov', '1921-02-18', '6 Melody Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Katey Vuitte', '1949-11-27', '9 Namekagon Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('May Skittreal', '1985-10-20', '8937 Fisk Avenue', 'Agender');
insert into student (name, birth_date, address, gender) values ('Noemi Watson', '1976-09-13', '66 Holy Cross Avenue', 'Female');
insert into student (name, birth_date, address, gender) values ('Flora Oxbury', '1960-05-08', '456 Dottie Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Germayne Pentecost', '2007-01-22', '6447 1st Point', 'Male');
insert into student (name, birth_date, address, gender) values ('Bobinette Lamball', '1931-08-11', '0665 Moulton Pass', 'Female');
insert into student (name, birth_date, address, gender) values ('Marcille Reglar', '1945-03-23', '6 Hansons Court', 'Female');
insert into student (name, birth_date, address, gender) values ('Ray Blackadder', '1937-10-06', '51 Helena Trail', 'Male');
insert into student (name, birth_date, address, gender) values ('Eleanor Buckby', '1979-07-26', '7664 Butterfield Court', 'Female');
insert into student (name, birth_date, address, gender) values ('Emelyne Proback', '1952-03-26', '57460 Walton Court', 'Polygender');
insert into student (name, birth_date, address, gender) values ('Caesar Cakes', '1992-07-22', '0 Di Loreto Plaza', 'Male');
insert into student (name, birth_date, address, gender) values ('Pattin Maryska', '1932-07-17', '78 Mccormick Avenue', 'Male');
insert into student (name, birth_date, address, gender) values ('Joan Shotbolt', '1990-04-26', '2543 Graceland Alley', 'Female');
insert into student (name, birth_date, address, gender) values ('Carroll Brakewell', '1987-11-22', '950 Farmco Center', 'Female');
insert into student (name, birth_date, address, gender) values ('Annadiana Kermott', '2015-04-19', '487 Norway Maple Alley', 'Female');
insert into student (name, birth_date, address, gender) values ('Lemar Lindenman', '1994-10-01', '1855 1st Pass', 'Male');
insert into student (name, birth_date, address, gender) values ('Sylas Castellanos', '1986-11-10', '6 Leroy Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Rhoda Beales', '1911-06-19', '56648 Kingsford Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Lani Jenteau', '1928-12-29', '7762 Starling Center', 'Female');
insert into student (name, birth_date, address, gender) values ('Raff Penhaleurack', '1960-06-14', '55356 Transport Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Gretal Gillani', '1930-02-17', '21154 Briar Crest Road', 'Female');
insert into student (name, birth_date, address, gender) values ('Cathy Krysztofiak', '1907-05-24', '59893 Spaight Point', 'Female');
insert into student (name, birth_date, address, gender) values ('Onfre Sansum', '1939-08-29', '90732 Crownhardt Circle', 'Male');
insert into student (name, birth_date, address, gender) values ('Rocky De Giorgio', '1980-08-17', '738 Paget Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Inglis Skerrett', '1953-01-17', '1240 Eggendart Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Ellen Szachniewicz', '1939-02-05', '439 Buell Terrace', 'Female');
insert into student (name, birth_date, address, gender) values ('Nestor Dugue', '2002-12-03', '083 Macpherson Lane', 'Male');
insert into student (name, birth_date, address, gender) values ('Adams Gradwell', '1937-12-23', '4425 Elka Place', 'Male');
insert into student (name, birth_date, address, gender) values ('Ophelia Tilney', '1991-06-07', '15210 Eastwood Court', 'Female');
insert into student (name, birth_date, address, gender) values ('Ealasaid Fletham', '1946-10-06', '47 Almo Terrace', 'Bigender');
insert into student (name, birth_date, address, gender) values ('Lindon Newbury', '1988-06-12', '30490 Express Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Violetta Dunning', '1932-09-10', '882 Lawn Crossing', 'Female');
insert into student (name, birth_date, address, gender) values ('Ingrid Batalini', '2004-10-26', '10 Forest Lane', 'Female');
insert into student (name, birth_date, address, gender) values ('Cordy Colnett', '1905-12-14', '44 Manley Junction', 'Female');
insert into student (name, birth_date, address, gender) values ('Ettore Oller', '1914-07-17', '66 Killdeer Avenue', 'Male');
insert into student (name, birth_date, address, gender) values ('Sophi Magovern', '1972-09-14', '40 Moulton Junction', 'Non-binary');
insert into student (name, birth_date, address, gender) values ('Lynda Kellaway', '1911-02-09', '66417 Melody Street', 'Non-binary');
insert into student (name, birth_date, address, gender) values ('Cello Crimmins', '1971-01-16', '8 Raven Center', 'Male');
insert into student (name, birth_date, address, gender) values ('Tessi Pessel', '1911-12-05', '45464 Mandrake Plaza', 'Female');
insert into student (name, birth_date, address, gender) values ('Codi Scholes', '1940-11-04', '73 Scott Hill', 'Male');
insert into student (name, birth_date, address, gender) values ('Jyoti Jennemann', '1949-06-24', '500 Carey Junction', 'Female');
insert into student (name, birth_date, address, gender) values ('Garik Loud', '2012-10-10', '1787 Mandrake Parkway', 'Male');
insert into student (name, birth_date, address, gender) values ('Jen Derrell', '1906-07-04', '4 Raven Place', 'Female');
insert into student (name, birth_date, address, gender) values ('Fletcher Vinnick', '1945-08-06', '4 Utah Drive', 'Male');
insert into student (name, birth_date, address, gender) values ('Murdoch Ankers', '1937-11-16', '33752 Sloan Terrace', 'Male');
insert into student (name, birth_date, address, gender) values ('Celestia Caldroni', '1955-01-27', '6895 Farmco Street', 'Female');
insert into student (name, birth_date, address, gender) values ('Byrann Soppeth', '1995-03-30', '15 Clyde Gallagher Road', 'Male');
insert into student (name, birth_date, address, gender) values ('Robers Atlay', '2005-08-06', '31648 Colorado Trail', 'Male');
insert into student (name, birth_date, address, gender) values ('Cooper Kimbrey', '1986-02-11', '0992 Burrows Point', 'Male');
insert into student (name, birth_date, address, gender) values ('Lindi Renon', '1972-11-06', '9613 Sycamore Park', 'Female');
insert into student (name, birth_date, address, gender) values ('Danila Clemerson', '1935-10-07', '10423 Anniversary Trail', 'Female');
insert into student (name, birth_date, address, gender) values ('Faber Studholme', '1946-11-04', '8 Sheridan Center', 'Male');
insert into student (name, birth_date, address, gender) values ('Aeriela Osorio', '1918-01-29', '294 Hooker Junction', 'Female');
insert into student (name, birth_date, address, gender) values ('Dayna Rue', '1903-11-25', '08726 Buell Crossing', 'Female');
insert into student (name, birth_date, address, gender) values ('Isa Harrop', '2010-09-24', '2909 Tomscot Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Aluino Doggrell', '1999-08-14', '18073 Raven Way', 'Male');
insert into student (name, birth_date, address, gender) values ('Felicity Argont', '1905-05-17', '60 Claremont Hill', 'Female');
insert into student (name, birth_date, address, gender) values ('Timothee Colmore', '1984-05-25', '6257 Chive Alley', 'Male');
insert into student (name, birth_date, address, gender) values ('Graeme Kilcoyne', '1972-10-07', '084 Luster Terrace', 'Male');
insert into student (name, birth_date, address, gender) values ('Carmelle Broek', '1931-06-27', '97 Mayfield Pass', 'Female');
insert into student (name, birth_date, address, gender) values ('Neysa Battram', '1959-03-26', '2761 Grover Drive', 'Female');
insert into student (name, birth_date, address, gender) values ('Lezlie Goodley', '2014-12-28', '386 Forest Park', 'Female');
insert into student (name, birth_date, address, gender) values ('Titus Smalley', '1967-05-12', '46 Service Plaza', 'Male');
insert into student (name, birth_date, address, gender) values ('Berkeley Collett', '2010-01-04', '53610 Nobel Hill', 'Genderfluid');
insert into student (name, birth_date, address, gender) values ('Kerwin Cuffe', '1975-03-27', '96689 Mitchell Court', 'Male');
insert into student (name, birth_date, address, gender) values ('Arman Chastanet', '1980-04-28', '92714 Sunbrook Circle', 'Male');
insert into student (name, birth_date, address, gender) values ('Davita Phizackarley', '1964-03-16', '240 Scott Park', 'Female');
insert into student (name, birth_date, address, gender) values ('Anderson Baitman', '2011-01-18', '6 Beilfuss Alley', 'Male');